version: '3.8'

services:
  api-core:
    build: .
    container_name: kipu_core_python
    ports:
      - "8002:8000"
    env_file:
      - .env
    restart: always
    networks:
      - red_infraestructura
      - dokploy-network

networks:
  red_infraestructura:
    external: true
  dokploy-network:
    external: true