version: '3.8'

services:
  api-core:
    build: .
    container_name: kipu_core_python
    ports:
      - "8002:8000"
    env_file:
      - .env
    # Esto permite que el código se actualice en el contenedor al editarlo (solo para desarrollo)
    volumes:
      - .:/app
    restart: always
    networks:          # ← mismo nivel que ports, volumes, etc.
      - red_infraestructura

networks:
  red_infraestructura:
    external: true
