version: "3.8"
 
services:
  api-core:
    build: .
    container_name: kipu_core_python
    ports:
      - "8002:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    depends_on:
      - redis
    networks:
      - red_infraestructura
 
  redis:
    image: redis:7-alpine
    container_name: kipu_redis
    restart: always
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
    networks:
      - red_infraestructura
 
networks:
  red_infraestructura:
    external: true
